name: workflow_management_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

#----------------------PACKAGES---------------------------#

dependencies:
  flutter:
    sdk: flutter

 # State Management
  get: ^4.6.6
  get_storage: ^2.1.1
  
  cupertino_icons: ^1.0.6
  iconsax: ^0.0.8

  google_fonts: ^6.2.1
  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.2.0
  url_launcher: ^6.2.6
  connectivity_plus: ^6.0.3
  image_picker: ^1.1.1
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.1.0
  date_picker_timeline: ^1.2.6
  sqflite: ^2.3.3+1
  flutter_staggered_animations: ^1.1.1
  flutter_local_notifications: ^17.1.2
#  flutter_native_timezone: ^2.0.0
  flutter_timezone: ^1.0.8
  file_picker: ^8.0.3

  # Firebase
  firebase_core: ^2.31.1
  firebase_auth: ^4.19.6
  cloud_firestore: ^4.17.4
  google_sign_in: ^6.2.1
  firebase_storage: ^11.7.6
  cached_network_image: ^3.3.1
  webview_flutter: ^4.8.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0



flutter:


  uses-material-design: true

  
  #---------------------------LOCAL ASSETS -------------------#
  assets:
    - assets/
    - assets/images/animations/
    - assets/images/on_boarding_images/
    - assets/images/user/
    - assets/icons/
    - assets/logos/
  
  #---------------------------LOCAL FONTS -------------------#


  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
